name: FRONTEND LINT TEST

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    lint:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                working-directory: ./client
        strategy:
            matrix:
                os:
                  - ubuntu-latest
                  - macos-latest
                  - windows-latest
                node-version:
                  - 14
                  - 16
                architecture:
                  - x64
        name: USING NODE ${{ matrix.node-version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        steps:
            - name: CHECK-OUT GIT REPOSITORY
              uses: actions/checkout@v3

            - name: SETUP NODE
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  architecture: ${{ matrix.architecture }}

            - name: INSTALL PROJECT DEPENDENCIES (YARN)
              run: yarn install

            - name: ESLINT CHECK
              run: yarn eslint:debug

            - name: PRETTIER FORMAT CHECK
              run: yarn prettier:check


            - name: STYLELINT CHECK
              run: yarn stylelint